# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - docker-compose -f docker/docker-compose.yml build
  up:
    cmds:
      - docker-compose -f docker/docker-compose.yml up -d
  down:
    cmds:
      - docker-compose -f docker/docker-compose.yml down
  restart:
    cmds:
      - docker-compose -f docker/docker-compose.yml restart