version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      SERVICES: ${SERVICES:-s3,lambda}
      AWS_DEFAULT_REGION: ap-southeast-1
      PERSISTENCE: 1
      DEBUG: ${DEBUG-1}
      HOSTNAME_EXTERNAL: localstack
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # for lambda
  golang:
    build:
      context: ..
      dockerfile: docker/golang/Dockerfile
    ports:
      - "7766:7766"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET=test
    volumes:
      - ../golang:/app
