// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package s3play

import (
	"github.com/katsuokaisao/localstack/infra/s3"
	"github.com/katsuokaisao/localstack/usecase/s3play"
)

// Injectors from wire.go:

func SetApplication() (*Application, error) {
	config, err := provideConfig()
	if err != nil {
		return nil, err
	}
	s3Component, err := provideS3Component(config)
	if err != nil {
		return nil, err
	}
	s3Repository, err := s3.NewS3Repository(s3Component)
	if err != nil {
		return nil, err
	}
	s3PlayUseCase := s3play.NewS3PlayUseCase(s3Repository)
	application := NewApplication(s3PlayUseCase)
	return application, nil
}
